#!/bin/bash

CONF_FILE="os-release"
DOC_URL="https://help.ubuntu.com/lts/ubuntu-help/index.html"
DOCUMENTATION_URL="https://help.ubuntu.com/22.04/ubuntu-help/index.html"

# If there is at least one argument, assume the first argument
# is the documentation url.
if [ "$#" -gt 0 ]; then
  DOC_URL="$1"
fi
echo "DOCUMENTATION_URL=\"$DOC_URL\"" >> "$CONF_FILE"